download:
  # Default download url
  url: 'http://feed.omgili.com/5Rh5AMTrc4Pv/mainstream/posts/'
  # Path where downloads will go
  path: 'tmp'

file_list:
  # Path where files will be extracted to
  entry_path: 'tmp/xml'
  # Path where archives will be loaded
  path: 'tmp'

# Redis config
redis:
  host: 'localhost'
  port: 6379
  db: ''
  list: 'NEWS_XML'